---
- name: Copy bash dotfiles
  copy:
    dest: "{{ dotdir }}"
    src: .dotfiles/bash
    owner: "{{ host_username }}"
    group: "{{ host_username }}"
    mode: 0755

- name: Select Debian dircolors
  ansible.builtin.command: mv "{{ dotdir }}/bash/.dircolors_debian" "{{ dotdir }}/bash/.dircolors"
  when: ansible_facts['os_family'] == "Debian"

- name: Select Redhat dircolors
  ansible.builtin.command: mv "{{ dotdir }}/bash/.dircolors_centos" "{{ dotdir }}/bash/.dircolors"
  when: ansible_facts['os_family'] == "Redhat"

- name: Remove Debian dircolors
  ansible.builtin.file:
    path: "{{ dotdir }}/bash/.dircolors_debian"
    state: "absent"
  when: ansible_facts['os_family'] == "Redhat"

- name: Remove Redhat dircolors
  ansible.builtin.file:
    path: "{{ dotdir }}/bash/.dircolors_centos"
    state: "absent"
  when: ansible_facts['os_family'] == "Debian"

- name: Stow bash dotfiles
  ansible.builtin.command: stow -Rv {{ item }}
  args:
    chdir: "{{ dotdir }}"
  loop:
    - bash

