---
- name: Stop filen daemon
  ansible.builtin.command: systemctl stop filen-sync
  become: true

- name: Clean filen installation
  ansible.builtin.file:
    path: "{{ host_homedir }}/.filen-cli"
    state: "absent"

- name: Recreate filen installation dir
  ansible.builtin.file:
    path: "{{ host_homedir }}/.filen-cli"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create temporary stow directory
  ansible.builtin.file:
    path: "/tmp/filen/bin"
    state: directory

- name: "Install filen-cli (version {{ filen_cli_ver }})"
  get_url:
    url: "https://github.com/FilenCloudDienste/filen-cli/releases/download/v{{ filen_cli_ver }}/filen-cli-v{{ filen_cli_ver }}-linux-x64"
    dest: "/tmp/filen/bin/filen-cli"
    mode: '755'

- name: Move filen-cli executable to global path
  include_role:
    name: copy_and_stow
  vars:
    prg_name: filen
    src_dir: "/tmp" 
    dest_dir: "{{ install_root }}"
    become_usr: root

- name: Clean temporary stow directory
  ansible.builtin.file:
    path: "/tmp/filen"
    state: absent

- name: Overwrite filen-cli systemd service file
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  loop:
    - filen-sync.service
  become_user: root

- name: Copy filen syncPairs definition
  ansible.builtin.copy:
    src: ".filen-cli/syncPairs.json"
    dest: "{{ host_homedir }}/.filen-cli"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
