---
- name: Clean xscreensaver installation
  apt:
    name:
      - libopengl-xscreensaver-perl
      - xscreensaver-data
      - xscreensaver-data-extra
      - xscreensaver-gl
      - xscreensaver-gl-extra
      - xscreensaver-screensaver-bsod
      - xscreensaver-screensaver-dizzy
    state: absent
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Clean xscreensaver default configs
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "/etc/X11/app-defaults/XScreenSaver*"
  become: true

- name: Install required packages
  apt:
    name:
      - intltool
      - libgtk-3-dev
      - libxml2-dev
      - libsystemd-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libx11-dev
      - build-essential
      - libpam0g-dev
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Clean package cache and dependencies
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Clean build directory
  file:
    path: "{{ work_dir }}"
    state: "absent"

- name: Recreate build directory
  file:
    path: "{{ work_dir }}"
    state: "directory"

- name: "Fetch xscreensaver (version {{ xscreensaver_version }})"
  get_url:
    url: "https://www.jwz.org/xscreensaver/xscreensaver-{{ xscreensaver_version }}.tar.gz"
    dest: "{{ work_dir }}"

- name: Uncompress xscreensaver package
  unarchive:
    src: "{{ work_dir }}/xscreensaver-{{ xscreensaver_version }}.tar.gz"
    dest: "{{ work_dir }}"
    remote_src: yes

- name: Configure xscreensaver
  command: "./configure --prefix=/usr/local/stow/xscreensaver-{{ xscreensaver_version }}"
  args:
    chdir: "{{ work_dir }}/xscreensaver-{{ xscreensaver_version }}"

- name: Compile xscreensaver
  command: make
  args:
    chdir: "{{ work_dir }}/xscreensaver-{{ xscreensaver_version }}"

- name: Install xscreensaver
  command: make install
  args:
    chdir: "{{ work_dir }}/xscreensaver-{{ xscreensaver_version }}"
  become: true

- name: clean build directory
  file:
    path: "{{ work_dir }}"
    state: "absent"

