---
- name: Install base packages
  apt:
    name:
      - autojump
      - build-essential
      - clang-format
      - git
      - pylint
      - python3-virtualenv
      - screen
      - silversearcher-ag
      - stow
      - vim
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Clean package cache and dependencies
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Create nvim stow directory
  ansible.builtin.file:
    path: "{{ nvim_bindir }}"
    state: directory

- name: Pull nvim appimage from github
  get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: "{{ nvim_bindir }}/nvim"
    mode: 0755

- name: Stow nvim
  ansible.builtin.command: stow -Rv {{ item }}
  args:
    chdir: "{{ install_root }}"
  with_items:
    - neovim

- name: Create (n)vim virtual env and install pynvim and black in it
  ansible.builtin.pip:
    virtualenv: "{{ host_homedir }}/.venv/nvim"
    name:
      - black
      - pynvim
  become_user: "{{ ansible_user }}"
