---
- name: Compile and install {{ dwm_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ dwm_name }}"
    repo: https://git.suckless.org/dwm
    commit: "{{ dwm_commit }}"
    install_dir: "{{ dwm_installdir }}"
    fetch: git

- name: Compile and install {{ dmenu_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ dmenu_name }}"
    repo: https://git.suckless.org/dmenu/
    commit: "{{ dmenu_commit }}"
    install_dir: "{{ dmenu_installdir }}"
    fetch: git

- name: Compile and install dwmblocks
  include_role:
    name: dwmblocks

- name: Copy dwm helpers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dwm_installdir }}/bin/{{ item | basename }}"
    mode: 0755
  with_fileglob: "{{ dwm_name }}/*-wrapper"

- name: Stow dwm and auxiliary programs
  ansible.builtin.command: stow --dotfiles -Rv {{ item }}
  args:
    chdir: "{{ install_root }}"
  loop:
    - "{{ dwm_name }}"
    - "{{ dmenu_name }}"
