---
- name: Install X11 dev packages for dwm compilation
  apt:
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Compile and install {{ dwm_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ dwm_name }}"
    repo: https://git.suckless.org/dwm
    commit: "{{ dwm_commit }}"
    install_dir: "{{ dwm_installdir }}"
    fetch: git

- name: Compile and install {{ dmenu_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ dmenu_name }}"
    repo: https://git.suckless.org/dmenu/
    commit: "{{ dmenu_commit }}"
    install_dir: "{{ dmenu_installdir }}"
    fetch: git

- name: Compile and install dwmblocks
  include_role:
    name: dwmblocks

- name: Install dwm helpers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dwm_installdir }}/bin/{{ item | basename }}"
    mode: 0755
  with_fileglob: "{{ dwm_name }}/*-wrapper"

- name: Stow dwm and auxiliary programs
  ansible.builtin.command: stow --dotfiles -Rv {{ item }}
  args:
    chdir: "{{ install_root }}"
  loop:
    - "{{ dwm_name }}"
    - "{{ dmenu_name }}"

- name: Create xsession file for dwm
  copy:
    dest: /usr/share/xsessions/old-x-session.desktop
    src: "{{ dwm_name }}/usr/share/xsessions/old-x-session.desktop"
    owner: root
    group: root
    mode: 0644
  become: true
