---
- name: Clean build directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: absent

- name: Recreate build directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory

- name: Pull "{{ repo }}" from git
  git:
    repo: "{{ repo }}"
    dest: "{{ work_dir }}"
    version: "{{ commit }}"
  when: fetch == "git"

- name: Copy "{{ repo }}"
  copy:
    dest: "{{ work_dir }}"
    src: "{{ copy_item }}"
  # Why on earth is this alway executed ?
  when: fetch == "copy"
  loop_control:
    loop_var: copy_item
  with_fileglob: "{{ repo }}/*"

- name: Fetch "{{ repo }}"
  get_url:
    url: "{{ repo }}"
    dest: "{{ work_dir }}"
  when: fetch == "url"

- name: Patch source tree
  ansible.builtin.command: git apply {{ item }}
  args:
    chdir: "{{ work_dir }}"
  # Sort patches so that they are applied in consistent order
  loop: "{{ query('fileglob', '{{ prg_name }}/patch/*.patch') | sort }}"

- import_tasks: make.yaml
  when: make_system == "make"

- import_tasks: cmake.yaml
  when: make_system == "cmake"

- import_tasks: ninja.yaml
  when: make_system == "ninja"

- name: Remove build dir
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: absent
