---
- name: Clean build directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: "absent"

- name: Recreate build directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: "directory"

- name: Pull "{{ repo }}" from git
  git:
    repo: "{{ repo }}"
    dest: "{{ work_dir }}"
    version: "{{ commit }}"
  when: fetch == "git"

- name: Copy "{{ repo }}"
  copy:
    dest: "{{ work_dir }}"
    src: "{{ item }}"
  with_fileglob: "{{ repo }}/*"
  when: fetch == "copy"

- name: Fetch "{{ repo }}"
  get_url:
    url: "{{ repo }}"
    dest: "{{ work_dir }}"
  when: fetch == "url"

- name: Patch source tree
  ansible.builtin.command: git apply {{ item }}
  args:
    chdir: "{{ work_dir }}"
  # Sort patches so that they are applied in consistent order
  loop: "{{ query('fileglob', 'files/prg/{{ prg_name }}/patch/*') | sort }}"

- import_tasks: make.yaml
  when: make_system == "make"

- import_tasks: cmake.yaml
  when: make_system == "cmake"

- name: Remove build dir
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: "absent"

