#!/bin/bash
# set -x
# Startup script for dwl - launches clients a la xinitrc
# use with: dwl -s dwl-init.sh

declare -r WP_DIR="${HOME}/Pictures/wallpapers"

[[ -x "${HOME}/.screenlayout/wl-default.sh" ]] && "${HOME}/.screenlayout/wl-default.sh"
[[ -n "$(which dwm-screensaver-wrapper)" ]] && { swayidle -w timeout 300 "dwm-screensaver-wrapper -w" & }
[[ -n "$(which swaybg)" ]] && { swaybg -m fit -i "$(find ${WP_DIR} -type f | sort -R | head -1)" & }
[[ -x "${HOME}/bin/pulse_monitor" ]] && { "${HOME}/bin/pulse_monitor" & }
[[ -x "${HOME}/bin/dwmblocks" ]] && { "${HOME}/bin/dwmblocks" -w & }

# End with somebar, which will consume the status info provided by dwl
[[ -n "$(which somebar)" ]] && somebar

# If we are here, somebar exited / crashed. Close STDIN so that dwl does not hang
exec <&-
