---
- name: "Check if program {{ dest_dir }}/{{ prg_name }} is already there"
  stat:
    path: "{{ dest_dir }}/{{ prg_name }}"
  register: stow_there

- name: Unstow {{ prg_name }}
  ansible.builtin.command: stow --dotfiles -Dv "{{ prg_name }}"
  args:
    chdir: "{{ dest_dir }}"
  become_user: "{{ become_usr }}"
  when: stow_there.stat.exists

- name: "Remove {{ prg_name }} directory"
  ansible.builtin.file:
    path: "{{ dest_dir }}/{{ prg_name }}"
    state: absent
  when: stow_there.stat.exists

- name: "Copy {{ prg_name }} directory"
  copy:
    dest: "{{ dest_dir }}"
    src: "{{ src_dir }}/{{ prg_name }}"
    owner: "{{ become_usr }}"
    mode: "{{ install_mode }}"
  become_user: "{{ become_usr }}"

- name: Restow {{ prg_name }}
  ansible.builtin.command: stow --dotfiles -Rv {{ prg_name }}
  args:
    chdir: "{{ dest_dir }}"
  become_user: "{{ become_usr }}"
