---
- name: Copy directories
  copy:
    dest: "{{ dest_dir }}"
    src: "{{ src_dir }}/{{ item }}"
    owner: "{{ become_usr }}"
    mode: 0755
  with_items: "{{ prg_names }}"
  become_user: "{{ become_usr }}"

- name: Stow directories
  ansible.builtin.command: stow --dotfiles -Rv {{ item }}
  args:
    chdir: "{{ dest_dir }}"
  with_items: "{{ prg_names }}"

