#!/bin/bash

# No way to get the current sink in use... use the default
_current_sink="$(pactl get-default-sink)"

if [[ "$_current_sink" != "" ]]
then
  case "$1" in
  "up")
    pactl set-sink-volume $_current_sink +5%
    ;;
  "dn")
    pactl set-sink-volume $_current_sink -5%
    ;;
  "mt")
    pactl set-sink-mute $_current_sink toggle
    ;;
  "gv")
    _vol=$(pactl get-sink-volume "$_current_sink" | awk '/Volume: front/{ print $5 }' | sed 's/[%|,]//g')
    _mut=$(pactl get-sink-mute   "$_current_sink" | awk '{ print $2}')
    if [ "$_mut" == "yes" ]; then
      _m="m"
    else
      _m=""
    fi
    if [ "$_vol" == "" ]; then
      echo "-"
    else
      echo "${_vol}%${_m}"
    fi
    ;;
  "sk")
    echo "$_current_sink" ;;
  esac
else
  case "$1" in
  "gv"|"sk")
    echo "-" ;;
  esac
fi

