#!/bin/bash

_current_sink=$(pacmd list-sinks | grep -A 1 '* index' | tail -1 | cut -d ' ' -f2 | sed -e 's/[<>]//g')

if [ "$_current_sink" != "" ]
then
    case "$1" in
    up)
        pactl set-sink-volume $_current_sink +5%
        ;;
    dn)
        pactl set-sink-volume $_current_sink -5%
        ;;
    mt)
        pactl set-sink-mute $_current_sink toggle
        ;;
    gv)
        _sts=$(pactl list sinks | grep -A 10 "Name: $_current_sink" | awk '/Volume: front/{ print $5 }; /Mute:/{ print $2 }' | sed 's/[%|,]//g')
        _vol=$(echo $_sts | cut -d ' ' -f 2)
        _mut=$(echo $_sts | cut -d ' ' -f 1)
        if [ "$_mut" == "yes" ]; then
            _m="m"
        else
            _m=""
        fi
        if [ "$_vol" == "" ]; then
            echo "-"
        else
            echo "${_vol}%${_m}"
        fi
        ;;
    sk)
        echo $_current_sink ;;
    esac
else
    case "$1" in
    gv|sk)
        echo "-" ;;
    esac
fi

