---
- name: Remove interception installation directory ({{ intercept_installdir }})
  ansible.builtin.file:
    path: "{{ intercept_installdir }}"
    state: "absent"

- name: Compile and install {{ intercept_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ intercept_name }}"
    repo: https://gitlab.com/interception/linux/tools.git
    install_dir: "{{ intercept_installdir }}"
    make_system: cmake
    fetch: git

- name: Compile and install {{ caps2esc_name }}
  include_role:
    name: fbi
  vars:
    prg_name: "{{ caps2esc_name }}"
    repo: https://gitlab.com/interception/linux/plugins/caps2esc.git
    install_dir: "{{ intercept_installdir }}"
    make_system: cmake
    fetch: git

# TODO: really support multiple plugins
- name: Compile local plugins
  include_role:
    name: fbi
  vars:
    prg_name: swap_mouse
    repo: prg/interception-tools/plugins
    install_dir: "{{ intercept_installdir }}"
    make_system: make
    fetch: copy
  when: install_swap_mouse

- name: Stow compiled programs
  ansible.builtin.command: stow --dotfiles -Rv {{ item }}
  args:
    chdir: "{{ install_root }}"
  loop:
    - "{{ intercept_name }}"

- name: Clean interception config dir
  ansible.builtin.file:
    path: "{{ intercept_configdir }}"
    state: "absent"
  become_user: root

- name: Create interception config dir
  ansible.builtin.file:
    path: "{{ intercept_configdir }}"
    state: directory
    mode: 0755
  become_user: root

- name: Copy interception-tools configs
  ansible.builtin.copy:
    src: "files/prg/{{ intercept_name }}/etc/{{ item }}"
    dest: "{{ intercept_configdir }}"
    mode: 0755
  loop:
    - interception
    - systemd
  become_user: root

- name: Remove unwanted plugins
  ansible.builtin.file:
    path: "{{ intercept_configdir }}/interception/udevmon.d/{{ item }}"
    state: "absent"
  loop:
    - swap_mouse.yaml
  when: not install_swap_mouse
  become_user: root

- name: Stow interception-tools configs
  ansible.builtin.command: stow --dotfiles -Rv interception
  args:
    chdir: /etc/stow
  become_user: root

