---
- name: Compile and install {{ intercept_name }}
  include_role:
    name: install_from_git
  vars:
    prg_name: "{{ intercept_name }}"
    repo: https://gitlab.com/interception/linux/tools.git
    install_dir: "{{ intercept_installdir }}"
    make_system: cmake

- name: Compile and install {{ caps2esc_name }}
  include_role:
    name: install_from_git
  vars:
    prg_name: "{{ caps2esc_name }}"
    repo: https://gitlab.com/interception/linux/plugins/caps2esc.git
    install_dir: "{{ caps2esc_installdir }}"
    make_system: cmake

- name: Stow compiled programs
  ansible.builtin.command: stow -Rv {{ item }}
  args:
    chdir: "{{ install_root }}"
  loop:
    - "{{ intercept_name }}"

- name: Create stow dir in /etc
  ansible.builtin.file:
    path: /etc/stow/interception
    state: directory
    mode: 0755
  become_user: root

- name: Copy interception-tools configs
  ansible.builtin.copy:
    src: "files/prg/{{ intercept_name }}/etc/{{ item }}"
    dest: /etc/stow/interception
    mode: 0755
  loop:
    - interception
    - systemd
  become_user: root

- name: Stow interception-tools configs
  ansible.builtin.command: stow -Rv interception
  args:
    chdir: /etc/stow
  become_user: root

