---
- hosts: desktop
  vars_files: ../configuration.yaml
  vars:
  become: true

  roles:
    - common_pkg
    - role: headless
      become_user: "{{ ansible_user }}"
    - desktop_pkg
    - dwm
    - interception

  tasks:
    - name: Stow desktop environment
      include_role:
        name: copy_and_stow
      vars:
        prg_names: [ cmus, x ]
        src_dir: "{{ src_dotdir }}"
        dest_dir: "{{ dst_dotdir }}"
        become_usr: "{{ ansible_user }}"

    - name: Fix gdm3 Xsession file (Ubuntu 22.04)
      copy:
        dest: /etc/gdm3/Xsession
        src: etc/gdm3/Xsession
        owner: root
        group: root
        mode: 0755
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['lsb']['release'] == "22.04"

    - name: Create xsession file for dwm
      copy:
        dest: /usr/share/xsessions/old-x-session.desktop
        src: usr/share/xsessions/old-x-session.desktop
        owner: root
        group: root
        mode: 0644

