---
- hosts: desktop
  vars_files: ../configuration.yaml
  become: true

  roles:
    - base
    - headless
    - x
    - wayland
    - interception

  tasks:
    - name: Install desktop packages
      apt:
        name:
          - cmus
          - mono-runtime
          - xdotool
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Stow desktop environment
      include_role:
        name: copy_and_stow
      vars:
        prg_name: cmus
        src_dir: "{{ src_dotdir }}"
        dest_dir: "{{ dst_dotdir }}"
        become_usr: "{{ ansible_user }}"
