---
- hosts: desktop
  vars_files: ../configuration.yaml
  vars:
  become: true

  roles:
    - base
    - role: headless
      become_user: "{{ ansible_user }}"
    - x
    - wayland
    - interception

  tasks:
    - name: Install desktop packages
      apt:
        name:
          - cmus
          - mono-runtime
          - xdotool
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Stow desktop environment
      include_role:
        name: copy_and_stow
      vars:
        prg_names: [ cmus ]
        src_dir: "{{ src_dotdir }}"
        dest_dir: "{{ dst_dotdir }}"
        become_usr: "{{ ansible_user }}"

